### ISSUE TITLE
First parameter of funcs should be value (props[prop])

### ISSUE THREAD

**Issue by mikestopcontinues** [brunobertolini/styled-by#4]
Hi! I realize this is a breaking change, but I believe it's worth it. See the following:

Before:
```js
by('size', (props) => pxToRem(props['size']))
by('colorName', (props) => namesToHex[props['colorName']])
```

After:
```js
by('size', pxToRem)
by('colorName', (name) => namesToHex[name])
```

I suggest the signature `(value, props)`. This would allow you to compose chains of functions (a la `R.pipe` or `_.flow`), and it would also allow you to reuse logic across components. (For instance, that `pxToRem` function.

**Comment by brunobertolini** [comment]
Hi Mike, sorry for the delay, I was very busy in the last few months. 
I like this strategy, and will appreciate a PR, because, well, I will continue busy in the nexts few months 😄

**Comment by mikestopcontinues** [comment]
Swell! I'll send one along soon.
